### ISSUE TITLE
HTML, CSS and ES6 Best Practice Review

### ISSUE THREAD

**Issue by bushmusi** [vikipretium/LeaderBoard#2]
### Hi **Vigenish**, You have done a great job so far. 
**Everything you did is great but we have a few suggestions in your codebase.**

1. You have used better semantics on your page. what we suggest you is in your [`index.html`](https://github.com/vikipretium/LeaderBoard/blob/dev/src/index.html#L13) we suggest you to use `h1` tag in your `section` tag.
2. You have used the right tags for your submit inputs. We kindly suggest you to use `form` tag [here](https://github.com/vikipretium/LeaderBoard/blob/b8e8628c1fe30c8a9329d63a26289547de3d17e9/src/index.html#L24-L26)

**Comment by vikipretium** [comment]
Thank you @bushmusi. I'll fix it as soon as possible.
